_target_: agent.hypo_code_lm.HypothesisCodeAgent
_recursive_: False

horizon: ${max_actions_per_trial}
filter_actions: False
prompt_type: "default"  # default, react, reflexion, cot

model: "gpt-4o-mini-2024-07-18"  # gpt-4o-mini-2024-07-18, gpt-4o-2024-08-06, o3-mini-2025-01-31, o1-mini-2024-09-12
temperature: 0.0
max_tokens: 1024


system_msg_path: "./agent/prompts/system_human_conj.txt"
hyp_gen_msg_path: "./agent/prompts/hyp_gen_func.txt"

infer_state: False  # use LM to infer state, if False use ground truth state
gen_n_hypothesis: 16  
add_elim_hypothesis: True  # add eliminated hypothesis to prompt
